<MangaSearchPage>
    MDTextField:
        id: SearchFieldID
        hint_text: "Type in a manga"
        #font_name: "meiryo.ttc"
        font_name: "./NotoSansCJKtc_ttf/NotoSansCJKtc-Regular.ttf"
        font_contex: "./NotoSansCJKtc_ttf/NotoSansCJKtc-Regular.ttf"
        size_hint:(0.5,0.1)
        pos_hint:{'center_x': 0.5, 'center_y': 0.5}
        on_text_validate: root.get_manga_query_data()
        text_language: "ja" 
        #on_text: self.insert_text(self.text, False)